### ISSUE TITLE
Have program listen on a port for incomming http requests

### ISSUE THREAD

**Issue by baigm** [liu118/Outward#1]
Please enhance the functionality of the tool so that it is able to serve content on a listening port. 

Example 1. Query for interface eth0 returns all parameters

$ curl localhost:8080/eth0
{
   "ipaddr": "192.168.0.1",
   "netmask": "255.255.255.0",
   "broadcast": "192.168.0.255"
}

Example 2. Query for IP address of eth0 only

$ curl localhost:8080/eth0?ipaddr
{
     "ipaddr": "192.168.0.1"
}

Example 3. Query for netmask and broadcast of interface Wlan0

$ curl localhost:8080/wlan0?netmask&broadcast
{
    "netmask: "255.255.255.0",
    "broadcast": "10.0.103.255"
}

**Comment by liu118** [comment]
@baigm 
fixed at 72e3590
