### ISSUE TITLE
Handle different ifconfig output formats

### ISSUE THREAD

**Issue by zpallin** [liu118/Outward#3]
I noticed on my machine that the pattern of the **inet config** looks like this:

`inet 10.0.100.178  netmask 255.255.252.0  broadcast 10.0.103.255`

Whereas your version has different terms used for the keys: "inet addr" and "Bcast" for example.

For the record, my net-tools version is: `net-tools 2.10-alpha`

Can you make a change that handles my system's version of `ifconfig` as well, and perhaps an easy way to add other aliases in the future?

**Comment by liu118** [comment]
@zpallin  fix at commit 4a84c27
